jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Git Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: adopt
        java-version: '11'
    - continue-on-error: true
      name: Start Redis Server
      uses: supercharge/redis-github-action@1.4.0
    - continue-on-error: true
      name: Run Tests
      run: mvn clean test jacoco:report -Dgithub=true
    - continue-on-error: true
      name: Upload Test Coverage Report
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        files: ./target/site/jacoco/jacoco.xml
        flags: unit-tests
        verbose: true
name: Java CI with Maven
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
